version: "3.9"

services:

  authdb:
    image: postgres
    volumes:
      - ./auth_service/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=microUser
      - POSTGRES_PASSWORD=superTajneHas0
    ports:
      - "8081:5432"
    restart: always
    networks:
      - cafemicro

  authdjango:
    build:
      context: ./auth_service/
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./auth_service:/code
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - authdb
    restart: always
    networks:
      - cafemicro

  supplierdb:
    image: postgres
    volumes:
      - ./supplier_service/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=microUser
      - POSTGRES_PASSWORD=superTajneHas0
    ports:
      - "8011:5432"
    restart: always
    networks:
      - cafemicro

  supplierdjango:
    build:
      context: ./supplier_service/
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - ./supplier_service:/code
    ports:
      - "8010:8010"
    env_file: .env
    depends_on:
      - supplierdb
      - authdb
      - authdjango
    restart: always
    networks:
      - cafemicro


networks:
  cafemicro: